services:
    frontend:
        container_name: production-analysis-frontend
        image: production-analysis-frontend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4200:4200"
        environment:
            - NODE_ENV=production
            - PORT=4200
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4200" ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
